Instantiate App of Apps in argocd-helm module
camptocamp/camptocamp-devops-stack pull request #340
Opened 2020-12-03 10:37 UTC by raphink

2020-12-03 12:04 UTC, mcanevet requested changes

2020-12-03 12:04 UTC, mcanevet commented on modules/argocd-helm/variables.tf
> +}
We should group this 2 variables into a complexe one

2020-12-03 12:04 UTC, mcanevet commented on modules/eks-aws/main.tf
> +  base_domain = var.base_domain
Pleas align `=` symbol

2020-12-03 12:04 UTC, mcanevet commented on modules/eks-aws/main.tf
> +  enable_efs                      = var.enable_efs
Please remove extra spaces before `=` symbol

2020-12-03 12:04 UTC, mcanevet commented on modules/k3os-libvirt/main.tf
> +
Please remove this

2020-12-03 12:04 UTC, mcanevet commented
I guess we should add a linting step into the pipeline...

2020-12-03 13:03 UTC, raphink commented
I'm keeping the complex variables PR into a separate branch (https://github.com/raphink/camptocamp-devops-stack/tree/app_of_apps_complex_vars) so we can do that later

2020-12-04 07:46 UTC, mcanevet commented
We need the same for aks-azure

2020-12-04 15:41 UTC, raphink commented
Superceded by #351

2020-12-04 15:41 UTC, closed without merging