Instantiate the app of apps inside the argocd-helm module
camptocamp/camptocamp-devops-stack pull request #351
Opened 2020-12-04 15:41 UTC by raphink

This puts the app of apps helm release inside the argocd-helm module, and refactors the variables for more clarity.

2020-12-04 15:42 UTC, raphink commented
Tests on https://katacoda.com/raphink/scenarios/devops-stack successful

2020-12-05 10:16 UTC, raphink commented
@mcanevet Tests with EKS module successful (training stack).

2020-12-05 10:22 UTC, raphink commented
@mcanevet could you test the other stacks (in particular Azure)?

2020-12-07 09:53 UTC, mcanevet requested changes

2020-12-07 09:53 UTC, mcanevet commented on modules/aks-azure/main.tf
> +  loki_bucket_name                = "",
Triggers this error:
```
Error: Unexpected comma after argument
On .terraform/modules/cluster/modules/aks-azure/main.tf line 90: Argument
definitions must be separated by newlines, not commas. An argument definition
must end with a newline.
```

2020-12-07 15:55 UTC, mcanevet approved these changes

2020-12-07 15:57 UTC, merged